### ISSUE TITLE
BungieApiBuilder workflow is broken

### ISSUE THREAD

**Issue by ryanhorath** [EndGameGl/DotNetBungieAPI#10]
Maybe I am missing something, but there is no way to actually get an IBungieClient as indicated by the "Basic Client Setup" page. That page says that BungieApiBuilder.GetApiClient() takes an Action&lt;BungieClientConfiguration&gt;. I believe it is *supposed* to. But in the actual code it takes an Action&lt;IBungieClientBuilder&gt;. Same for the UseBungieApiClient() extension method. Internally, GetApiClient() then news up *another* copy of IBungieClientBuilder (new BungieClientBuilder() on line 59). BungieClientBuilder in turns constructs everything in its constructor, including a new copy of the needed BungieClientConfiguration class. Thus, there is no way to inject your configuration into the process.

I tried getting around this by inheriting from BungieClientBuilder, but the ClientConfiguration property only has a getter and cannot be set in the new class. I tried copying and creating an entirely new BungieClientBuilder, but the ServiceConfigurator class it uses is set to internal protection.

I don't see how this ever worked. The GetApiClient method needs to have its parameter fixed to what is indicated by the "Basic Client Setup" page. And that configuration needs to be passed down into the BungieClientBuilder through its constructor.

**Comment by EndGameGl** [comment]
I updated https://github.com/EndGameGl/DotNetBungieAPI/wiki/Basic-client-setup page with actual examples.
Is there any specific need for settings to be injected?
Here is the example of creating new instance: https://github.com/EndGameGl/Atheon/blob/development/src/Atheon/Atheon/Services/BungieClientProvider.cs#L64

**Comment by ryanhorath** [comment]
Thanks for the response, updating the page, & the example code. Now I see what I was missing. You have to reach down all the way into the service and set some properties. This is not good practice, but it works. I don't want to be picky and tell you how you should write your code, and I do appreciate the work put into this. Thanks for the assistance.

As a side note, I also don't think the GetApiClient method needs to exist. It only appears to differ from the UseBungieApiClient method by setting up Logging, which is an unwanted side effect. I would think calling a method that sets up a Bungie API client and getting logging setup as a side effect of that process would be an unwanted surprise for most callers. The services should be able to gracefully handle no logging service being present. That's just my two cents.

Again, thanks for the assistance.
