### ISSUE TITLE
JSON serialization performance

### ISSUE THREAD

**Issue by breeky-dev** [EndGameGl/DotNetBungieAPI#5]
Currently, serializing and deserializing in JSON a List of DestinyHistoricalStatsPeriodGroup is quite slow using the default  IBungieNetJsonSerializer. For a list of 3000 activities, it takes around 40s to parse the json. 

Is there any tips to improve performance when serializing a List of DestinyHistoricalStatsPeriodGroup into JSON (for indexedDb)?

**Comment by EndGameGl** [comment]
@samuel-chp https://github.com/dotnet/runtime/issues/40386

**Comment by breeky-dev** [comment]
I found an ugly workaround for now: I've selected only some properties from each DestinyHistoricalStatsPeriodGroup in the list I want to give to JS (for example, the "kills" or "assists" per game). 

Then I use marshal types with the new JS interop from net7 (https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?view=aspnetcore-7.0), passing arrays of double essentially.

It's very ugly and not very handy but I went from 40s of transfer to 1.2s.

**Comment by EndGameGl** [comment]
Well, I guess for now making a proper serializer for this kind of thing is impossible after all?

**Comment by geometrikal** [comment]
Try publishing with AOT enabled and see if the slowness resolves. It is a pain as the AOT compilation takes a long time, but in my application parsing a 6MB json went from around 6 seconds to almost nothing.

**Comment by EndGameGl** [comment]
@geometrikal the problem is that whole manifest takes like 150mb of space

**Comment by breeky-dev** [comment]
Well for the manifest it's manageable, I just handle the download with JS directly so that I don't have to transfer a lot of data with Blazor JS interop. It becomes annoying when I want to access a big chunk of data from indexed db multiple times and process it with blazor. The transfer times are quite long.

The AOT indeed works great. I went from 4s to 0.4s once the app is published. Yet in development it remains an issue to wait this long.

**Comment by EndGameGl** [comment]
@samuel-chp you can do lazy loading on definitions, like, save them in memory for later use
