### ISSUE TITLE
BungieNetUserInfo is null on private profiles but not nullable in code

### ISSUE THREAD

**Issue by MoonieGZ** [EndGameGl/DotNetBungieAPI#8]
https://github.com/EndGameGl/DotNetBungieAPI/blob/55b85c1063e7304d6f5233d9327fdc4b1a3ddff7/DotNetBungieAPI.Models/GroupsV2/GroupUserBase.cs#L12

Example that produces null reference exception:

```
var clan = await _bungieClient.ApiAccess.GroupV2.GetMembersOfGroup(5109614);
foreach(var player in clan.Response.Results)
    Console.WriteLine(player.BungieNetUserInfo.MembershipId);
```

When it gets to [this profile](https://www.bungie.net/7/en/User/Profile/3/4611686018483767904) it will crash due to BungieNetUserInfo being null. This happens everywhere it's needed but this is an example I have on hand.

**Comment by EndGameGl** [comment]
Uploaded new version with this property now nullable
