### ISSUE TITLE
Incorrect execution times on Linux

### ISSUE THREAD

**Issue by MoonieGZ** [EndGameGl/DotNetBungieAPI#9]
https://github.com/EndGameGl/DotNetBungieAPI/blob/207edf8aa4f04a2a65100975275d0c5d2d418b24/DotNetBungieAPI/Services/Implementations/DefaultDotNetBungieApiHttpClient.cs#L294

On Linux host this line reports values in milliseconds instead of seconds but works perfectly on windows.

**Comment by EndGameGl** [comment]
Issued a fix for this issue, tell me if it worked

**Comment by MoonieGZ** [comment]
Fixed by cfdb2a9. Thanks!
